### ISSUE TITLE
[DimStorage 1.15.2-3.1.1] Crash on loading client and server

### ISSUE THREAD

**Issue by bloodyraoul** [Edivad99/DimStorage#23]
SERVER CRASH on load : 
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	DimStorage (dimstorage) has failed to load correctly
java.lang.IllegalAccessError: no such constructor: edivad.dimstorage.blocks.DimTank.<init>()void/newInvokeSpecial
]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:183) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {re:classloading}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:613) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202] {}

******************************************************************************************************
CLIENT CRASH :
it doesnt seems to be DimStorage related but my modpack works well with previous version
---- Minecraft Crash Report ----
// I'm sorry, Dave.

Time: 4/21/20 3:30 PM
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:91) ~[?:?] {re:classloading}
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23) ~[?:?] {re:classloading}
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19) ~[?:?] {re:classloading}
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:112) ~[?:?] {re:classloading}
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:352) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_484_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.1] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$30(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$5120/843325140.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:217) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:243) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:212) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:421) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.47.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$461/1760443245.call(Unknown Source) [forge-1.15.2-31.1.47.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

**Comment by Edivad99** [comment]
Could you send me the full error on pastebin?

**Comment by Edivad99** [comment]
What version of TheOneProbe do you have installed?

**Comment by Edivad99** [comment]
The second log that you write, has nothing to do with DimStorage it seems a problem with mekanism: basic_fluid_tank
