### ISSUE TITLE
NPE when using /setblock to create dimstorage:dimensional_tank

### ISSUE THREAD

**Issue by blackd** [Edivad99/DimStorage#44]
**Describe the bug**

**Configuration**
Mod version: 6.0.0
Forge version: 39.0.64
Minecraft version: 1.18.1
Are you playing on server?: No

**To Reproduce**
1. execute command */setblock ~1 ~ ~ dimstorage:dimensional_tank destroy*
2. game crashes with:
```
java.lang.NullPointerException: Cannot invoke "edivad.dimstorage.api.Frequency.copy()" because "freq" is null
	at edivad.dimstorage.api.AbstractDimStorage.<init>(AbstractDimStorage.java:15) ~[DimStorage-1.18.1-6.0.0.jar%23170!/:6.0.0] {re:classloading}
	at edivad.dimstorage.storage.DimTankStorage.<init>(DimTankStorage.java:29) ~[DimStorage-1.18.1-6.0.0.jar%23170!/:6.0.0] {re:classloading}
	at edivad.dimstorage.plugin.DimTankPlugin.createDimStorage(DimTankPlugin.java:16) ~[DimStorage-1.18.1-6.0.0.jar%23170!/:6.0.0] {re:classloading}
	at edivad.dimstorage.manager.DimStorageManager.getStorage(DimStorageManager.java:174) ~[DimStorage-1.18.1-6.0.0.jar%23170!/:6.0.0] {re:classloading}
	at edivad.dimstorage.network.TankState.getFluidStorageServer(TankState.java:48) ~[DimStorage-1.18.1-6.0.0.jar%23170!/:6.0.0] {re:classloading}
	at edivad.dimstorage.network.TankState.update(TankState.java:27) ~[DimStorage-1.18.1-6.0.0.jar%23170!/:6.0.0] {re:classloading}
	at edivad.dimstorage.blockentities.BlockEntityDimTank.onServerTick(BlockEntityDimTank.java:68) ~[DimStorage-1.18.1-6.0.0.jar%23170!/:6.0.0] {re:classloading}
	at edivad.dimstorage.blockentities.BlockEntityFrequencyOwner.serverTick(BlockEntityFrequencyOwner.java:72) ~[DimStorage-1.18.1-6.0.0.jar%23170!/:6.0.0] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:768) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.redirect$bdg000$redirectTick(Level.java:2082) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixi
	at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.m
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:324) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blu
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:868) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23448!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
```
**Expected behavior**
the game not to crash

**Comment by Edivad99** [comment]
The question is: Why are you doing this?

**Comment by blackd** [comment]
pasting a schematic
